"""Repo-local curated topic graph support.

Topic data lives inside each repository under ``.regin/topics``. The
approved graph is human-governed; scans refresh refs for existing
topics from the working tree but never create approved topics.

Implementation is split across ``core`` (constants/types/IO/paths),
``scan`` (validation/scanning), and ``route`` (lookup/rendering); this
package re-exports the public surface.
"""

from __future__ import annotations

from lib.topics.core import (
    DEFAULT_EXCLUDES,
    EDGE_TYPES,
    IGNORED_DIRS,
    IGNORED_SUFFIXES,
    REF_ROLES,
    ROLE_ORDER,
    SCHEMA_VERSION,
    TOPIC_FILE,
    TOPIC_LOCAL_FILE,
    TOPIC_STATUSES,
    TOPICS_DIR,
    TopicGraphError,
    ValidationResult,
    _valid_id,
    bootstrap,
    empty_graph,
    is_generated_path,
    load_graph,
    load_graph_merged,
    load_local_graph,
    match_glob,
    merge_graphs,
    normalize,
    read_json,
    repo_name,
    save_graph,
    save_local_graph,
    seed_topics,
    slugify,
    topic_dir,
    topic_local_path,
    topic_path,
    utc_now,
    write_json,
)
from lib.topics.scan import (
    delete_topic,
    git_lines,
    install_pre_commit_hook,
    install_topic_hooks,
    is_repo_content_path,
    list_repo_files,
    promote_all_topics,
    promote_topic,
    refs_for_topic,
    scan,
    staged_files,
    tracked_files,
    update_topic,
    validate,
)
from lib.topics.route import (
    best_topic_for_text,
    generate_topic_router_skill,
    match_topic,
    ordered_refs,
    read_wiki_pages,
    route_topic,
    topic_detail,
    topic_summary,
    topic_wiki_content,
    wiki_paths_for_topic,
)
from lib.topics.term_weights import rebuild_query_df


__all__ = [
    "DEFAULT_EXCLUDES",
    "EDGE_TYPES",
    "IGNORED_DIRS",
    "IGNORED_SUFFIXES",
    "REF_ROLES",
    "ROLE_ORDER",
    "SCHEMA_VERSION",
    "TOPIC_FILE",
    "TOPIC_LOCAL_FILE",
    "TOPIC_STATUSES",
    "TOPICS_DIR",
    "TopicGraphError",
    "ValidationResult",
    "bootstrap",
    "delete_topic",
    "empty_graph",
    "generate_topic_router_skill",
    "git_lines",
    "install_pre_commit_hook",
    "install_topic_hooks",
    "is_generated_path",
    "is_repo_content_path",
    "list_repo_files",
    "load_graph",
    "load_graph_merged",
    "load_local_graph",
    "match_glob",
    "best_topic_for_text",
    "match_topic",
    "merge_graphs",
    "normalize",
    "ordered_refs",
    "promote_all_topics",
    "promote_topic",
    "read_json",
    "read_wiki_pages",
    "rebuild_query_df",
    "refs_for_topic",
    "repo_name",
    "route_topic",
    "save_graph",
    "save_local_graph",
    "scan",
    "seed_topics",
    "slugify",
    "staged_files",
    "topic_detail",
    "topic_dir",
    "topic_local_path",
    "topic_path",
    "topic_summary",
    "topic_wiki_content",
    "tracked_files",
    "update_topic",
    "utc_now",
    "validate",
    "wiki_paths_for_topic",
    "write_json",
]
