"""Generate derived wiki files from approved topic graphs."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from lib.topics import ROLE_ORDER, slugify, topic_dir, validate
from lib.topics.graph_io import load_authoritative_graph


def wiki_dir(repo_path: str | Path) -> Path:
    return topic_dir(repo_path) / "wiki"


def generate_wiki(repo_path: str | Path) -> list[Path]:
    """Regenerate `wiki/index.md` only.

    Per-topic wiki files (`wiki/<topic-id>.md`) are owned by the
    accept-from-proposal flow — `lib/topics/proposals.py::_persist_per_topic_wiki`
    slices the agent's rich narrative out of the proposal's wiki.md
    and writes it there. Re-running `generate_wiki` used to clobber
    those rich files with `render_topic_page` boilerplate — a
    projection of the graph's structured fields that adds no
    information not already in the graph itself.

    Post-fix: the function still writes the index, which IS useful
    as an entry point (it lists every topic with its intent line),
    and stays in sync with the graph. Per-topic files are
    untouched. If a topic exists in the graph but has no
    `wiki/<id>.md` (never went through accept), the index links to
    a missing file — surface that as a TODO in the topic's row in
    the future, don't clobber.

    `render_topic_page` stays exported for callers that want to
    materialize a per-topic boilerplate explicitly (e.g. CLI dev
    tools); it just isn't auto-applied any more.
    """
    result = validate(repo_path)
    if not result.ok:
        raise ValueError("; ".join(result.errors))

    graph = load_authoritative_graph(repo_path)
    out_dir = wiki_dir(repo_path)
    out_dir.mkdir(parents=True, exist_ok=True)

    index_path = out_dir / "index.md"
    index_path.write_text(render_index(graph, wiki_root=out_dir))
    return [index_path]


def _index_row(topic_id: str, topic: dict[str, Any], wiki_root: Path | None) -> str:
    """One index line. A topic whose `wiki/<id>.md` was never authored (bucket
    topics, never-drafted leaves) renders as plain text with a `no wiki yet`
    marker instead of a link to a file that doesn't exist — the index must
    never emit a dead link. When `wiki_root` is None the file can't be checked,
    so every row links (preserves the pure-render callers)."""
    label = topic.get("label", topic_id)
    intent = topic.get("intent", "")
    slug = slugify(topic_id)
    if wiki_root is not None and not (wiki_root / f"{slug}.md").exists():
        return f"- **{label}** — no wiki yet · {intent}"
    return f"- [{label}]({slug}.md) - {intent}"


def render_index(graph: dict[str, Any], wiki_root: Path | None = None) -> str:
    lines = [
        f"# Topic Wiki: {graph.get('repo', 'repo')}",
        "",
        "Generated from `.regin/topics/topics/` + `topic.local.json` overlay. Do not edit this file as source of truth.",
        "",
        "## Topics",
        "",
    ]
    for topic_id, topic in sorted(graph.get("topics", {}).items()):
        lines.append(_index_row(topic_id, topic, wiki_root))
    if not graph.get("topics"):
        lines.append("- No approved topics.")
    lines.append("")
    return "\n".join(lines)


def render_topic_page(topic_id: str, topic: dict[str, Any], topics: dict[str, Any]) -> str:
    lines = [
        f"# {topic.get('label', topic_id)}",
        "",
        "Generated from `.regin/topics/topics/` + `topic.local.json` overlay. Do not edit this file as source of truth.",
        "",
        "## Intent",
        "",
        topic.get("intent", ""),
        "",
        "## Aliases",
        "",
    ]
    aliases = topic.get("aliases", [])
    lines.extend([f"- `{alias}`" for alias in aliases] or ["- None"])
    lines.extend(["", "## References", ""])
    refs = sorted(topic.get("refs", []), key=_ref_sort_key)
    if refs:
        current_role = None
        for ref in refs:
            role = ref.get("role", "implementation")
            if role != current_role:
                current_role = role
                lines.extend([f"### {role.title()}", ""])
            lines.append(f"- `{ref.get('path', '')}`")
        lines.append("")
    else:
        lines.extend(["- No approved refs.", ""])

    lines.extend(["## Commands", ""])
    commands = topic.get("commands", [])
    lines.extend([f"- `{command}`" for command in commands] or ["- None"])

    lines.extend(["", "## Relationships", ""])
    edges = topic.get("edges", [])
    if edges:
        for edge in edges:
            target = edge.get("target")
            label = topics.get(target, {}).get("label", target)
            lines.append(f"- {edge.get('type', 'related')}: `{target}` ({label})")
    else:
        lines.append("- None")

    lines.extend(["", "## Globs", "", "### Include", ""])
    lines.extend([f"- `{glob}`" for glob in topic.get("include_globs", [])] or ["- None"])
    lines.extend(["", "### Exclude", ""])
    lines.extend([f"- `{glob}`" for glob in topic.get("exclude_globs", [])] or ["- None"])
    lines.append("")
    return "\n".join(lines)


def _ref_sort_key(ref: dict[str, Any]) -> tuple[int, str]:
    role = ref.get("role", "implementation")
    order = ROLE_ORDER.index(role) if role in ROLE_ORDER else len(ROLE_ORDER)
    return order, ref.get("path", "")
