"""Index approved-topic wiki pages into the dense pattern index.

Companion to `lib.patterns.pattern_router.index_patterns`: both write
into the same `pattern_docs` + `pattern_embeddings` + `patterns_fts`
trio so `route()` can fuse pattern hits and wiki hits with a single
RRF + cross-encoder pass. The discriminator is `pattern_docs.source_kind`
('pattern' vs 'wiki'); see migration 0010.

Source of truth for wiki content: per-topic markdown files at
`<repo>/.regin/topics/wiki/<slugify(topic_id)>.md`, written by the
proposal-accept flow (`lib/topics/proposals.py::_persist_per_topic_wiki`
and `lib/topics/graph_io.py::export_graph_to_disk`). Metadata (label,
intent, refs) comes from the approved graph itself via
`load_authoritative_graph`.

Auto-reindex: `lib/topics/apply.py::apply_diff` calls
`index_wikis_best_effort` after every successful export so the index
never drifts from the disk. Manual backfill via `regin wiki index`.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Optional

from lib.activity_log import get_activity_logger as _get_activity_logger


def _patterns_log():
    return _get_activity_logger("patterns")

from sqlalchemy import text as sa_text
from sqlmodel import select

from lib.orm import SessionLocal
from lib.orm.models import PatternDoc, PatternEmbedding, Repo
from lib.patterns.pattern_router import _hash, _upsert_fts
from lib.skills import skill_router
from lib.topics import slugify, topic_dir
from lib.topics.graph_io import load_authoritative_graph


def _wiki_slug(repo_name: str, topic_id: str) -> str:
    return f"wiki/{repo_name}/{topic_id}"


def _wiki_files(repo_path: str) -> dict[str, Path]:
    """Map `slugify(topic_id) -> Path` for every per-topic wiki file.

    Skips `index.md` (autogenerated by `generate_wiki`, not per-topic).
    """
    out: dict[str, Path] = {}
    base = topic_dir(repo_path) / "wiki"
    if not base.is_dir():
        return out
    for path in sorted(base.glob("*.md")):
        if path.name == "index.md":
            continue
        out[path.stem] = path  # path.stem is already the slugified topic id
    return out


def _build_pd_kwargs(
    *,
    repo: Repo,
    topic_id: str,
    topic: dict,
    wiki_path: Path,
) -> dict:
    """Build the keyword args for upserting a wiki PatternDoc row.

    `topic` is the dict slice from the approved graph's `topics` map.
    Falls back gracefully when label/intent are missing (treated as
    minimal metadata; the body still gets indexed).
    """
    label = (topic.get("label") if isinstance(topic, dict) else None) or topic_id
    return {
        "slug": _wiki_slug(repo.name, topic_id),
        "title": label,
        "file_path": str(wiki_path.resolve()),  # absolute; _body_at handles it
        "category": "wiki",
        "source_kind": "wiki",
        "repo_id": repo.id,
        # Not a PatternDoc column — popped by _persist_wiki_upserts for the
        # `repo:<name>` FTS tag. Repo association itself lives in repo_id.
        "repo_name": repo.name,
    }


def _description_for_wiki(topic_id: str, topic: dict) -> str:
    """Build the `description` slot the SkillRouter ranks against.

    Mirrors `pattern_router._description_slot` shape (`category | desc |
    tags`) so the reranker sees the same document format whether the
    row is a pattern or a wiki.
    """
    parts: list[str] = ["wiki"]
    intent = topic.get("intent") if isinstance(topic, dict) else None
    if isinstance(intent, str) and intent.strip():
        parts.append(intent.strip())
    refs = topic.get("refs") if isinstance(topic, dict) else None
    ref_paths: list[str] = []
    if isinstance(refs, list):
        for r in refs:
            if isinstance(r, dict):
                path = r.get("path")
                if isinstance(path, str):
                    ref_paths.append(path)
    if ref_paths:
        parts.append("refs: " + ", ".join(ref_paths[:8]))
    parts.append(f"topic:{topic_id}")
    return " | ".join(parts)


def _wiki_document_text(repo: Repo, topic_id: str, topic: dict, body: str) -> str:
    """`name | description | body` shape, kind:wiki tag in tag slot."""
    return skill_router.format_document(
        name=f"wiki {repo.name} {topic_id} {(topic.get('label') if isinstance(topic, dict) else '') or ''}".strip(),
        description=_description_for_wiki(topic_id, topic),
        body=body,
    )


def _delete_wiki_row(session, pd_id: int, slug: str) -> None:
    """Remove a wiki row + its embedding + its FTS entry."""
    session.execute(
        sa_text("DELETE FROM pattern_embeddings WHERE pattern_id = :pid"),
        {"pid": pd_id},
    )
    session.execute(
        sa_text("DELETE FROM patterns_fts WHERE slug = :slug"),
        {"slug": slug},
    )
    session.execute(
        sa_text("DELETE FROM pattern_docs WHERE id = :pid"),
        {"pid": pd_id},
    )


def _resolve_graph_for_index(
    repo: Repo,
    graph: Optional[dict],
    say,
) -> Optional[dict]:
    """Return the graph dict to index, or None if it can't be loaded.

    Caller-supplied `graph` short-circuits the drift-detecting
    `load_authoritative_graph` — see `index_wikis` docstring for why
    `apply_diff`'s bg thread MUST pass its own copy.
    """
    if graph is not None:
        return graph
    try:
        return load_authoritative_graph(repo.path)
    except Exception as exc:  # noqa: BLE001 — surface any load failure
        say(f"could not load graph for {repo.name}: {exc}")
        return None


def _load_existing_wiki_state(session, repo: Repo) -> tuple[dict, dict]:
    existing_rows = session.exec(
        select(PatternDoc)
        .where(PatternDoc.source_kind == "wiki")
        .where(PatternDoc.repo_id == repo.id)
    ).all()
    existing_by_slug = {pd.slug: pd for pd in existing_rows}
    existing_emb = {
        row.pattern_id: row
        for row in session.exec(
            select(PatternEmbedding).where(
                PatternEmbedding.pattern_id.in_([pd.id for pd in existing_rows] or [-1])
            )
        ).all()
    }
    return existing_by_slug, existing_emb


def _wiki_unchanged(
    pd_kwargs: dict,
    content_hash: str,
    model_id: str,
    existing_pd,
    prior_emb,
    force: bool,
) -> bool:
    return (
        not force
        and existing_pd is not None
        and prior_emb is not None
        and prior_emb.content_hash == content_hash
        and prior_emb.model_id == model_id
        and existing_pd.content_hash == content_hash
        and existing_pd.title == pd_kwargs["title"]
    )


def _classify_wiki_topic(
    repo: Repo,
    topic_id: str,
    topic,
    wiki_path: Path,
    existing_by_slug: dict,
    existing_emb: dict,
    model_id: str,
    force: bool,
) -> tuple[str, tuple]:
    """Return (kind, payload).
      'missing' — wiki body couldn't be read; payload=(reason,)
      'skip'    — hash unchanged; payload=(slug,)
      'plan'    — needs upsert+embed; payload=(pd_kwargs, body, desc, doc_text, hash)
    """
    try:
        body = wiki_path.read_text()
    except OSError as exc:
        return "missing", (str(exc),)
    pd_kwargs = _build_pd_kwargs(
        repo=repo, topic_id=topic_id, topic=topic, wiki_path=wiki_path,
    )
    topic_dict = topic if isinstance(topic, dict) else {}
    description = _description_for_wiki(topic_id, topic_dict)
    doc_text = _wiki_document_text(repo, topic_id, topic_dict, body)
    h = _hash(doc_text)
    existing_pd = existing_by_slug.get(pd_kwargs["slug"])
    prior_emb = existing_emb.get(existing_pd.id) if existing_pd else None
    if _wiki_unchanged(pd_kwargs, h, model_id, existing_pd, prior_emb, force):
        return "skip", (pd_kwargs["slug"],)
    return "plan", (pd_kwargs, body, description, doc_text, h)


def _plan_wiki_upserts(
    repo: Repo,
    topics: dict,
    wiki_paths: dict[str, Path],
    existing_by_slug: dict,
    existing_emb: dict,
    model_id: str,
    force: bool,
    say,
) -> tuple[list[tuple], set[str], int, int]:
    """Decide per-topic action; returns (upsert_plan, seen_slugs, skipped, missing)."""
    upsert_plan: list[tuple] = []
    seen_slugs: set[str] = set()
    skipped = 0
    missing = 0
    for topic_id, topic in topics.items():
        if not isinstance(topic_id, str):
            continue
        wiki_path = wiki_paths.get(slugify(topic_id))
        if wiki_path is None:
            missing += 1
            continue
        kind, payload = _classify_wiki_topic(
            repo, topic_id, topic, wiki_path,
            existing_by_slug, existing_emb, model_id, force,
        )
        if kind == "missing":
            say(f"could not read wiki for {topic_id}: {payload[0]}")
            missing += 1
            continue
        if kind == "skip":
            seen_slugs.add(payload[0])
            skipped += 1
            continue
        # kind == "plan"
        seen_slugs.add(payload[0]["slug"])
        upsert_plan.append(payload)
    return upsert_plan, seen_slugs, skipped, missing


def _persist_wiki_upserts(upsert_plan: list[tuple]) -> list[tuple[int, str, str]]:
    """Apply pd_kwargs + FTS in one transaction. Returns
    `[(pd_id, doc_text, content_hash), ...]` for the embedding phase."""
    new_or_changed_pds: list[tuple[int, str, str]] = []
    with SessionLocal() as session:
        for pd_kwargs, body, description, doc_text, content_hash in upsert_plan:
            repo_name = pd_kwargs.pop("repo_name", "")
            existing_pd = session.exec(
                select(PatternDoc).where(PatternDoc.slug == pd_kwargs["slug"])
            ).first()
            if existing_pd is None:
                pd = PatternDoc(**pd_kwargs, content_hash=content_hash)
                session.add(pd)
                session.flush()
            else:
                for k, v in pd_kwargs.items():
                    setattr(existing_pd, k, v)
                existing_pd.content_hash = content_hash
                pd = existing_pd
            tag_names = ["kind:wiki", f"repo:{repo_name}"]
            _upsert_fts(session, pd, description, body, tag_names)
            new_or_changed_pds.append((pd.id, doc_text, content_hash))
        session.commit()
    return new_or_changed_pds


def _reconcile_wiki_deletes(existing_by_slug: dict, seen_slugs: set[str], say) -> int:
    """Delete DB rows whose slug isn't backed by a wiki file on disk."""
    to_delete = [pd for slug, pd in existing_by_slug.items() if slug not in seen_slugs]
    if not to_delete:
        return 0
    with SessionLocal() as session:
        for pd in to_delete:
            _delete_wiki_row(session, pd.id, pd.slug)
        session.commit()
    say(f"removed {len(to_delete)} stale wiki row(s)")
    return len(to_delete)


def _persist_wiki_embeddings(
    new_or_changed_pds: list[tuple[int, str, str]],
    model_id: str,
) -> int:
    import numpy as np
    texts = [doc_text for _pid, doc_text, _h in new_or_changed_pds]
    vectors = skill_router.embed(texts, model_id=model_id)
    dim = int(vectors.shape[1])
    now = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    indexed = 0
    with SessionLocal() as session:
        for (pd_id, _doc_text, content_hash), vec in zip(new_or_changed_pds, vectors):
            blob = np.asarray(vec, dtype="float32").tobytes()
            row = session.get(PatternEmbedding, pd_id)
            if row is None:
                row = PatternEmbedding(
                    pattern_id=pd_id,
                    content_hash=content_hash,
                    model_id=model_id,
                    dim=dim,
                    vector=blob,
                )
            else:
                row.content_hash = content_hash
                row.model_id = model_id
                row.dim = dim
                row.vector = blob
                row.updated_at = now
            session.add(row)
            indexed += 1
        session.commit()
    return indexed


def index_wikis(
    repo: Repo,
    *,
    force: bool = False,
    model_id: str = skill_router.EMBEDDING_MODEL_ID,
    progress=None,
    graph: Optional[dict] = None,
) -> dict:
    """Sync wiki PatternDoc rows + embeddings + FTS rows for one repo.

    Returns counts: `{indexed, skipped, removed, missing}`. `missing`
    counts topics present in the graph but with no wiki file on disk
    (informational; not an error — un-accepted topics are normal).

    Cross-store ordering: rows are upserted to SQL first, FTS refreshed
    in the same transaction, then embeddings encoded + saved in a
    second transaction. Matches `index_patterns()` exactly.

    `graph`: when the caller already holds the authoritative graph dict
    (typically `apply_diff`'s `_bg_reindex` thread, which captures the
    just-applied `diff.prospective_graph`), pass it through to skip
    `load_authoritative_graph`. That avoids a race where two consecutive
    applies have an in-flight bg thread observe `snap_hash != disk_hash`
    and trigger `_auto_seed_snapshot`, which would silently insert an
    extra `is_latest=1` snapshot. See `apply.py::_bg_reindex`.
    """
    skill_router.ensure_deps()

    def _say(msg: str) -> None:
        if progress is not None:
            progress(msg)

    repo_path = repo.path
    if not Path(repo_path).is_dir():
        _say(f"repo path missing on disk: {repo_path}")
        return {"indexed": 0, "skipped": 0, "removed": 0, "missing": 0}

    graph = _resolve_graph_for_index(repo, graph, _say)
    if graph is None:
        return {"indexed": 0, "skipped": 0, "removed": 0, "missing": 0}
    topics = (graph or {}).get("topics") or {}
    wiki_paths = _wiki_files(repo_path)
    _say(f"loaded {len(topics)} topic(s), {len(wiki_paths)} wiki file(s)")

    with SessionLocal() as session:
        existing_by_slug, existing_emb = _load_existing_wiki_state(session, repo)

    upsert_plan, seen_slugs, skipped, missing = _plan_wiki_upserts(
        repo, topics, wiki_paths, existing_by_slug, existing_emb,
        model_id, force, _say,
    )

    new_or_changed_pds = _persist_wiki_upserts(upsert_plan)
    _say(f"upserted {len(upsert_plan)} pattern_doc(s) + fts row(s)")

    removed = _reconcile_wiki_deletes(existing_by_slug, seen_slugs, _say)

    if not new_or_changed_pds:
        _say(f"nothing to embed (skipped={skipped} missing={missing} removed={removed})")
        if removed > 0 or upsert_plan:
            _patterns_log().write(
                "wikis_indexed", repo_name=repo.name, repo_id=repo.id,
                indexed=0, skipped=skipped, removed=removed, missing=missing,
            )
        return {"indexed": 0, "skipped": skipped, "removed": removed, "missing": missing}

    _say(f"encoding {len(new_or_changed_pds)} wiki page(s) for repo={repo.name}")
    indexed = _persist_wiki_embeddings(new_or_changed_pds, model_id)

    _patterns_log().write(
        "wikis_indexed", repo_name=repo.name, repo_id=repo.id,
        indexed=indexed, skipped=skipped, removed=removed, missing=missing,
    )
    return {"indexed": indexed, "skipped": skipped, "removed": removed, "missing": missing}


def index_wikis_best_effort(
    repo: Repo,
    *,
    progress=None,
    graph: Optional[dict] = None,
) -> Optional[dict]:
    """Embed if router deps are installed; otherwise log and return None.

    Called from the accept/restore paths in `lib/topics/apply.py` and
    `web/blueprints/topics/apply.py` so a missing embedding model never
    blocks the accept itself.

    `graph`: forwarded to `index_wikis`. See its docstring for why
    `apply_diff`'s bg thread MUST pass the just-applied graph.
    """
    try:
        return index_wikis(repo, progress=progress, graph=graph)
    except skill_router.DependencyError:
        return None
    except Exception as exc:  # noqa: BLE001 — accept must not fail because of indexing
        if progress is not None:
            progress(f"wiki indexer crashed for repo={repo.name}: {exc}")
        return None


__all__ = ["index_wikis", "index_wikis_best_effort"]
