<script setup>
import { ref, onMounted, computed } from 'vue'
import api from '../api'
import Card from '../components/Card.vue'
import Badge from '../components/Badge.vue'
import Button from '../components/ui/Button.vue'
import Icon from '../components/ui/Icon.vue'
import PatternCreateForm from '../components/PatternCreateForm.vue'
import PatternFolderImportModal from '../components/PatternFolderImportModal.vue'
import { useSkillImport } from '../composables/useSkillImport'
import { useProviderPaths } from '../composables/useProviderPaths'

const data = ref(null)
const loading = ref(true)
const showCreate = ref(false)
const folderVisible = ref(false)
const allTags = ref([])

const {
  importInput,
  onImportPick,
} = useSkillImport()

async function load() {
  loading.value = true
  const [skills, tags] = await Promise.all([
    api.get('/skills?include_deployments=1'),
    api.get('/tags').catch(() => []),
  ])
  data.value = skills
  allTags.value = tags || []
  loading.value = false
}

onMounted(load)

const { provider, enabledProviders, globalDir, projectSubpath, providerName, providerBadge } =
  useProviderPaths(data)
const deploymentsBySkill = computed(() => data.value?.deployments_by_skill || {})
const deploymentsByProject = computed(() => data.value?.deployments_by_project || [])
const projectDeployments = computed(() => (data.value?.deployments || []).filter(d => d.scope === 'project'))

function projectCount(skillId) {
  return (deploymentsBySkill.value[skillId] || []).filter(d => d.scope === 'project').length
}

const stateBadge = {
  in_sync: { color: 'green', label: 'deployed', scope: 'global' },
  drifted: { color: 'yellow', label: 'out of sync', scope: 'global' },
  deployed_only: { color: 'blue', label: 'orphan (source missing)' },
  source_only: { color: 'purple', label: 'not deployed' },
  project_only: { color: 'green', label: 'deployed', scope: 'project' },
}

const typeDescriptions = {
  auto: 'Auto-generated by a configured rule engine (e.g. grit). Regenerate from the skill detail page.',
  pattern: 'Source: patterns/<id>/SKILL.md. Pull folds deployed edits back into source.',
}
</script>

<template>
  <div v-if="loading" class="empty-state">Loading skills…</div>
  <div v-else>
    <header class="page-header">
      <div class="page-header-text">
        <div class="page-eyebrow">Library</div>
        <h1 class="page-title">Skills</h1>
        <p class="page-subtitle">Skill packs deployed globally and per-project.</p>
      </div>
      <div class="page-actions">
        <Badge color="blue" :label="`${data.total} global`" />
        <Badge color="green" :label="`${projectDeployments.length} project deploy${projectDeployments.length !== 1 ? 's' : ''}`" />
        <Badge v-if="data.drift_count" color="yellow" :label="`${data.drift_count} drifted`" />
        <Badge v-else color="gray" label="all in sync" />
        <span class="text-xs text-slate-400">enabled:</span>
        <Badge
          v-for="p in enabledProviders"
          :key="p.id"
          :color="p.id === provider.id ? 'blue' : 'gray'"
          :label="p.name"
        />
        <Button
          variant="secondary"
          aria-label="Batch import skills"
          @click="folderVisible = true"
        >
          <Icon name="folder-plus" :size="14" />
          Import
        </Button>
        <Button
          variant="primary"
          @click="showCreate = true"
        >
          <Icon name="plus" :size="14" />
          New skill
        </Button>
        <input ref="importInput" type="file" webkitdirectory multiple aria-label="Import skill folder" class="hidden" @change="onImportPick">
      </div>
    </header>

    <PatternFolderImportModal v-model:visible="folderVisible" @imported="load" />
    <PatternCreateForm v-if="showCreate" :tags="allTags" redirect-to="skills" @close="showCreate = false" />

    <h2 class="section-heading">Global · <code class="cell-code">{{ globalDir }}/</code></h2>

    <template v-for="typeName in ['auto', 'pattern']" :key="typeName">
      <Card v-if="data.by_type[typeName]?.length" :no-padding="true" class="mb-5">
        <div class="card-group-header">
          <h3 class="card-group-title">
            <code>{{ typeName }}</code>
            <span class="text-xs text-slate-400 font-normal ml-1">{{ data.by_type[typeName].length }} skill{{ data.by_type[typeName].length !== 1 ? 's' : '' }}</span>
          </h3>
          <p class="card-group-meta">{{ typeDescriptions[typeName] }}</p>
        </div>
        <table class="tbl" style="table-layout:fixed;width:100%">
          <colgroup>
            <col style="width:30%"><col style="width:14%"><col style="width:10%"><col style="width:46%">
          </colgroup>
          <thead>
            <tr><th>Skill</th><th>{{ providerName }}</th><th>Scope</th><th>Source</th></tr>
          </thead>
          <tbody>
            <tr v-for="r in data.by_type[typeName]" :key="r.id">
              <td>
                <router-link :to="r.href"
                  class="table-link focus-visible:outline-2 focus-visible:outline-blue-500">
                  <code>{{ r.id }}</code>
                </router-link>
                <Badge v-if="projectCount(r.id) > 0"
                  color="green"
                  :label="`also in ${projectCount(r.id)} project${projectCount(r.id) > 1 ? 's' : ''}`"
                  class="ml-2" />
              </td>
              <td>
                <Badge :color="stateBadge[r.state]?.color || 'gray'" :label="stateBadge[r.state]?.label || r.state" />
              </td>
              <td>
                <Badge v-if="stateBadge[r.state]?.scope" color="gray" :label="stateBadge[r.state].scope" />
                <span v-else class="text-slate-400 text-[12px]">—</span>
              </td>
              <td class="text-slate-500 truncate" :title="r.source"><code class="cell-code">{{ r.source }}</code></td>
            </tr>
          </tbody>
        </table>
      </Card>
    </template>

    <h2 class="section-heading">Per-project · <code class="cell-code">&lt;repo&gt;/{{ projectSubpath }}/</code></h2>

    <Card v-if="deploymentsByProject.length === 0" class="empty-state">
      No project-level deployments yet. Open any pattern skill and use
      <strong>Push to project</strong> to deploy it to a specific repo.
    </Card>

    <Card v-for="proj in deploymentsByProject" :key="proj.project_id" :no-padding="true" class="mb-5">
      <div class="card-group-header">
        <h3 class="card-group-title">
          <code>{{ proj.project_name }}</code>
          <span class="text-xs text-slate-400 font-normal ml-1">{{ proj.items.length }} skill{{ proj.items.length !== 1 ? 's' : '' }}</span>
        </h3>
        <p class="card-group-meta truncate" :title="proj.project_path">
          <code>{{ proj.project_path }}/{{ projectSubpath }}/</code>
        </p>
      </div>
      <table class="tbl" style="table-layout:fixed;width:100%">
        <colgroup>
          <col style="width:30%"><col style="width:18%"><col style="width:22%"><col style="width:30%">
        </colgroup>
        <thead>
          <tr><th>Skill</th><th>Provider</th><th>Deployed at</th><th>Path</th></tr>
        </thead>
        <tbody>
          <tr v-for="d in proj.items" :key="`${d.id}:${d.provider || 'active'}`">
            <td>
              <router-link :to="`/skills/${d.pattern_slug}`"
                class="table-link focus-visible:outline-2 focus-visible:outline-blue-500">
                <code>{{ d.pattern_slug }}</code>
              </router-link>
            </td>
            <td>
              <Badge color="gray" :label="providerBadge(d.provider)" />
            </td>
            <td class="text-xs text-slate-500 tabular-nums">{{ d.deployed_at }}</td>
            <td class="text-slate-500 truncate" :title="d.deployed_path"><code class="cell-code">{{ d.deployed_path }}</code></td>
          </tr>
        </tbody>
      </table>
    </Card>
  </div>
</template>
